version: "3"

services:
  api-service:
    image: "spring-boot-with-graphql"
    networks:
      - spring-boot-with-graphql-network
    ports:
      - 80:8080
    depends_on:
      - database

  mongodb-database:
    image: mongo:4.4.4
    container_name: "mongodb-database"
    networks:
      - spring-boot-with-graphql-network
    ports:
      - 27017:27017
    command: --smallfiles

networks:
  spring-boot-with-graphql-network:
