version: "3"

services:
  api-service:
    image: spring-boot-with-graphql
    networks:
      - spring-boot-with-graphql-network
    ports:
      - 80:8080
    depends_on:
      - mongodb-database

  mongodb-database:
    image: mongo:4.4.4
    container_name: mongodb-database
    networks:
      - spring-boot-with-graphql-network
    ports:
      - 27017:27017
    environment: # don't commit credentials to git
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test

networks:
  spring-boot-with-graphql-network:
